#!name=Pillow
#!desc=Pillow Premium
#!url=https://raw.githubusercontent.com/ryanyux/shadowrocket-module/main/modules/pillow.module

[MITM]
hostname = %APPEND% api.revenuecat.com

[Script]
Pillow=type=http-response,pattern=https:\/\/api\.revenuecat\.com\/v1\/(subscribers\/identify|receipts|subscribers\/\$PLAnonymousID%3A[0-9A-Z-]+),requires-body=1 ,script-path=https://raw.githubusercontent.com/ryanyux/shadowrocket-module/main/js/pillow.js
